//! Type-level dependency lists and computed event types.
//!
//! This module provides the building blocks for declaring which
//! entities a reactor handles and computing the discriminated union
//! event type from that list. Both the [`Reactor`](super::Reactor)
//! trait and the [wiring infrastructure](super::StoreBuilder) depend
//! on these types.
//!
//! # Type-level lists
//!
//! Entity lists are built from [`Cons`] and [`Nil`]:
//! `Cons<A, Cons<B, Nil>>`. The [`deps!`] macro provides sugar:
//! `deps![A, B]`.
//!
//! # Computed event types
//!
//! [`EntityList`] computes a discriminated union event type from
//! the list. `Cons<A, Cons<B, Nil>>` yields
//! `OneOf<(A::Id, A::Event), OneOf<(B::Id, B::Event), Never>>`.
//!
//! Consume events via the [`.on()`](OneOf::on) /
//! [`.exhaustive()`](Fold::exhaustive) chain, which guarantees
//! at compile time that every entity is handled. Use
//! [`.on_with_fallback()`](OneOf::on_with_fallback) instead of
//! `.on()` when a handler needs a recovery path - if the
//! primary handler fails, the fallback receives the error plus
//! the same `(Id, Event)` to reprocess from the errored state.

use std::future::Future;
use std::marker::PhantomData;
use std::pin::Pin;
use std::sync::Arc;

use crate::EventSourced;
use crate::lifecycle::Never;

/// Type-level cons cell for building linked lists of entities.
///
/// Forms a compile-time linked list:
/// `Cons<Position, Cons<TokenizedEquityMint, Nil>>`.
pub struct Cons<Head, Tail>(PhantomData<(Head, Tail)>);

/// Type-level empty list (nil).
///
/// Terminal element for type-level entity lists.
pub struct Nil;

/// Declares which entities a reactor handles.
///
/// Generated by the statement-position form of [`deps!`]:
///
/// ```ignore
/// deps!(RebalancingTrigger, [Position, TokenizedEquityMint]);
/// ```
///
/// This also generates [`HasEntity`] impls for each entity,
/// enabling ergonomic [`ReactorHarness::receive`] calls.
pub trait Dependent: Send + Sync {
    /// Type-level list of entities this reactor handles.
    type Dependencies: EntityList;
}

/// Enables sharing a `Dependent` impl via `Arc`.
impl<R: Dependent> Dependent for Arc<R> {
    type Dependencies = R::Dependencies;
}

/// Trait on type-level entity lists that computes the
/// discriminated union event type.
///
/// `Cons<A, Cons<B, Nil>>` yields
/// `OneOf<(A::Id, A::Event), OneOf<(B::Id, B::Event), Never>>`.
pub trait EntityList {
    type Event: Send;
}

impl EntityList for Nil {
    type Event = Never;
}

impl<Head: EventSourced, Tail: EntityList> EntityList for Cons<Head, Tail> {
    type Event = OneOf<(Head::Id, Head::Event), Tail::Event>;
}

/// Discriminated union of entity events, computed from a
/// type-level entity list.
///
/// `Cons<A, Cons<B, Nil>>` yields
/// `OneOf<(A::Id, A::Event), OneOf<(B::Id, B::Event), Never>>`.
///
/// Consume via the [`.on()`](Self::on) chain:
///
/// ```ignore
/// event
///     .on(|id, event| async move { self.on_a(id, event).await })
///     .on(|id, event| async move { self.on_b(id, event).await })
///     .exhaustive()
///     .await
/// ```
pub enum OneOf<Head, Tail> {
    Here(Head),
    There(Tail),
}

impl<Id, Event, Tail> OneOf<(Id, Event), Tail> {
    /// Handle the head entity in the union.
    ///
    /// The handler returns a future, which is boxed to unify
    /// types across all handlers in the chain. Call
    /// [`.exhaustive()`](Fold::exhaustive) after all handlers,
    /// then `.await` the result.
    pub fn on<'a, T, F, Fut>(self, handler: F) -> Fold<BoxFuture<'a, T>, Tail>
    where
        F: FnOnce(Id, Event) -> Fut,
        Fut: Future<Output = T> + Send + 'a,
    {
        match self {
            Self::Here((id, event)) => Fold::Done(Box::pin(handler(id, event))),
            Self::There(tail) => Fold::Remaining(tail),
        }
    }

    /// Like [`on`](Self::on), but with a recovery path.
    ///
    /// Runs `handler` first. If it returns `Err(error)`,
    /// runs `fallback` with the same `(Id, Event)` plus the
    /// error, allowing it to reprocess the event starting
    /// from the errored state.
    pub fn on_with_fallback<'a, O, E, F, Fut, G, GFut>(
        self,
        handler: F,
        fallback: G,
    ) -> Fold<BoxFuture<'a, Result<O, E>>, Tail>
    where
        Id: Clone + Send + 'a,
        Event: Clone + Send + 'a,
        F: FnOnce(Id, Event) -> Fut + Send + 'a,
        Fut: Future<Output = Result<O, E>> + Send + 'a,
        G: FnOnce(E, Id, Event) -> GFut + Send + 'a,
        GFut: Future<Output = Result<O, E>> + Send + 'a,
        O: Send + 'a,
        E: Send + 'a,
    {
        match self {
            Self::Here((id, event)) => Fold::Done(Box::pin(async move {
                let id_clone = id.clone();
                let event_clone = event.clone();
                match handler(id, event).await {
                    Ok(ok) => Ok(ok),
                    Err(error) => fallback(error, id_clone, event_clone).await,
                }
            })),
            Self::There(tail) => Fold::Remaining(tail),
        }
    }
}

impl<A> OneOf<A, Never> {
    /// Unwrap a single-entity event.
    ///
    /// Convenience for `Dependencies = deps![Entity]` where the
    /// computed event is `OneOf<(Id, Event), Never>`.
    pub fn into_inner(self) -> A {
        match self {
            Self::Here(inner) => inner,
            Self::There(never) => match never {},
        }
    }
}

/// Intermediate result from folding handlers over a [`OneOf`]
/// chain.
///
/// `Done(T)` means a handler already matched. `Remaining(tail)`
/// means no handler matched yet and more `.on()` calls are
/// needed. When the tail is [`Never`],
/// [`.exhaustive()`](Self::exhaustive) extracts the result.
pub enum Fold<T, Remaining> {
    Done(T),
    Remaining(Remaining),
}

/// Boxed future used for type erasure across `.on()` handler chains.
type BoxFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

impl<'a, T, Id, Event, Tail> Fold<BoxFuture<'a, T>, OneOf<(Id, Event), Tail>> {
    /// Handle the next entity in the union.
    ///
    /// The handler returns a future, which is boxed to match
    /// the type established by the first `.on()` call.
    pub fn on<F, Fut>(self, handler: F) -> Fold<BoxFuture<'a, T>, Tail>
    where
        F: FnOnce(Id, Event) -> Fut,
        Fut: Future<Output = T> + Send + 'a,
    {
        match self {
            Fold::Done(fut) => Fold::Done(fut),
            Fold::Remaining(one_of) => match one_of {
                OneOf::Here((id, event)) => Fold::Done(Box::pin(handler(id, event))),
                OneOf::There(tail) => Fold::Remaining(tail),
            },
        }
    }
}

impl<'a, O: Send + 'a, E: Send + 'a, Id, Event, Tail>
    Fold<BoxFuture<'a, Result<O, E>>, OneOf<(Id, Event), Tail>>
{
    /// Like [`on`](Fold::on), but with a recovery path.
    ///
    /// Runs `handler` first. If it returns `Err(error)`,
    /// runs `fallback` with the same `(Id, Event)` plus the
    /// error, allowing it to reprocess the event starting
    /// from the errored state.
    pub fn on_with_fallback<F, Fut, G, GFut>(
        self,
        handler: F,
        fallback: G,
    ) -> Fold<BoxFuture<'a, Result<O, E>>, Tail>
    where
        Id: Clone + Send + 'a,
        Event: Clone + Send + 'a,
        F: FnOnce(Id, Event) -> Fut + Send + 'a,
        Fut: Future<Output = Result<O, E>> + Send + 'a,
        G: FnOnce(E, Id, Event) -> GFut + Send + 'a,
        GFut: Future<Output = Result<O, E>> + Send + 'a,
    {
        match self {
            Fold::Done(fut) => Fold::Done(fut),
            Fold::Remaining(one_of) => match one_of {
                OneOf::Here((id, event)) => Fold::Done(Box::pin(async move {
                    let id_clone = id.clone();
                    let event_clone = event.clone();
                    match handler(id, event).await {
                        Ok(ok) => Ok(ok),
                        Err(error) => fallback(error, id_clone, event_clone).await,
                    }
                })),
                OneOf::There(tail) => Fold::Remaining(tail),
            },
        }
    }
}

impl<T> Fold<T, Never> {
    /// Extract the result once all entities are handled.
    ///
    /// Only available when every entity in the chain has a
    /// corresponding `.on()` handler -- [`Never`] guarantees
    /// exhaustiveness at compile time.
    pub fn exhaustive(self) -> T {
        match self {
            Self::Done(result) => result,
            Self::Remaining(never) => match never {},
        }
    }
}

/// Inject an entity's (Id, Event) pair by entity type.
///
/// For single-element lists (`Cons<E, Nil>`), a blanket impl
/// is provided. For multi-element lists, impls are generated
/// by [`register_entities!`] (called automatically by
/// [`deps!`]).
pub trait HasEntity<Entity: EventSourced>: EntityList {
    fn inject(id: Entity::Id, event: Entity::Event) -> Self::Event;
}

/// Blanket impl for single-element dependency lists.
///
/// Covers reactors with exactly one entity dependency (e.g.,
/// [`Projection`](crate::Projection)) without requiring
/// [`register_entities!`]. Multi-element lists get their impls
/// from the macro instead.
impl<Entity: EventSourced> HasEntity<Entity> for Cons<Entity, Nil> {
    fn inject(id: Entity::Id, event: Entity::Event) -> Self::Event {
        OneOf::Here((id, event))
    }
}

/// Build a type-level dependency list from entity types.
///
/// Has two forms, distinguished by syntax:
///
/// ## Type-position: `deps![...]`
///
/// Expands to a nested `Cons<..., Nil>` type. Use for
/// manual `Dependent` impls:
///
/// ```ignore
/// impl Dependent for MyReactor {
///     type Dependencies = deps![A, B];
/// }
/// ```
///
/// ## Statement-position: `deps!(Reactor, [...])`
///
/// Generates a [`Dependent`] impl (setting `Dependencies`)
/// and [`HasEntity`] impls for each entity. This is the
/// primary form -- the entity list is written once:
///
/// ```ignore
/// deps!(EventBroadcaster, [
///     TokenizedEquityMint,
///     EquityRedemption,
///     UsdcRebalance,
/// ]);
///
/// impl Reactor for EventBroadcaster {
///     // Dependencies comes from Dependent -- no duplication
///     type Error = Never;
///
///     async fn react(
///         &self,
///         event: <Self::Dependencies as EntityList>::Event,
///     ) -> Result<(), Self::Error> { ... }
/// }
/// ```
#[macro_export]
macro_rules! deps {
    // Statement-position: generate Dependent + HasEntity impls.
    ($reactor:ty, [$($entity:ty),+ $(,)?]) => {
        impl $crate::Dependent for $reactor {
            type Dependencies = $crate::deps![$($entity),+];
        }
        $crate::register_entities!($($entity),+);
    };

    // Type-position: expand to Cons chain.
    () => { $crate::Nil };
    ($head:ty $(, $tail:ty)* $(,)?) => {
        $crate::Cons<$head, $crate::deps![$($tail),*]>
    };
}

/// Generate [`HasEntity`] impls for each entity in a list.
///
/// This is the low-level building block used by the
/// statement-position form of [`deps!`]. Prefer using `deps!`
/// directly, which generates both [`Dependent`] and [`HasEntity`]
/// impls in one call.
///
/// Only use this directly for generic `Reactor` impls (like
/// [`SpyReactor`]) where `deps!` can't generate the `Dependent`
/// impl.
#[macro_export]
macro_rules! register_entities {
    // Single entity: blanket `HasEntity<E> for Cons<E, Nil>`
    // covers this case, so no macro-generated impl needed.
    ($single:ty) => {};

    // Multiple entities: generate HasEntity impls.
    ($($entity:ty),+ $(,)?) => {
        $crate::register_entities!(@impls [$($entity),+] [$($entity),+] []);
    };

    // All entities processed.
    (@impls [] [$($all:ty),+] [$($done:ty),*]) => {};

    // Generate HasEntity for the current entity, then recurse.
    (@impls [$current:ty $(, $rest:ty)*] [$($all:ty),+] [$($done:ty),*]) => {
        impl $crate::HasEntity<$current> for $crate::deps![$($all),+] {
            fn inject(
                id: <$current as $crate::EventSourced>::Id,
                event: <$current as $crate::EventSourced>::Event,
            ) -> <Self as $crate::EntityList>::Event {
                $crate::register_entities!(@wrap [$($done),*] $crate::OneOf::Here((id, event)))
            }
        }

        $crate::register_entities!(@impls [$($rest),*] [$($all),+] [$($done,)* $current]);
    };

    // No wrapping needed (entity is at head).
    (@wrap [] $expr:expr) => { $expr };

    // Wrap in OneOf::There for each entity before the current one.
    (@wrap [$_head:ty $(, $rest:ty)*] $expr:expr) => {
        $crate::OneOf::There($crate::register_entities!(@wrap [$($rest),*] $expr))
    };
}

#[cfg(test)]
mod tests {
    use async_trait::async_trait;
    use cqrs_es::DomainEvent;
    use serde::{Deserialize, Serialize};

    use super::*;
    use crate::JobQueue;

    #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
    struct Alpha {
        tag: String,
    }

    #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
    enum AlphaEvent {
        Born,
    }

    impl DomainEvent for AlphaEvent {
        fn event_type(&self) -> String {
            "AlphaBorn".into()
        }
        fn event_version(&self) -> String {
            "1".into()
        }
    }

    #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, thiserror::Error)]
    #[error("alpha error")]
    struct AlphaError;

    #[async_trait]
    impl EventSourced for Alpha {
        type Id = String;
        type Event = AlphaEvent;
        type Command = ();
        type Error = AlphaError;
        type Jobs = Nil;
        type Materialized = Nil;

        const AGGREGATE_TYPE: &'static str = "Alpha";
        const PROJECTION: Nil = Nil;
        const SCHEMA_VERSION: u64 = 1;

        fn originate(event: &AlphaEvent) -> Option<Self> {
            match event {
                AlphaEvent::Born => Some(Self {
                    tag: "alpha".into(),
                }),
            }
        }

        fn evolve(_: &Self, _: &AlphaEvent) -> Result<Option<Self>, AlphaError> {
            Ok(None)
        }

        async fn initialize(
            (): (),
            _jobs: &JobQueue<Self::Jobs>,
        ) -> Result<Vec<AlphaEvent>, AlphaError> {
            Ok(vec![AlphaEvent::Born])
        }

        async fn transition(
            &self,
            (): (),
            _jobs: &JobQueue<Self::Jobs>,
        ) -> Result<Vec<AlphaEvent>, AlphaError> {
            Ok(vec![])
        }
    }

    #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
    struct Beta {
        tag: String,
    }

    #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
    enum BetaEvent {
        Spawned,
    }

    impl DomainEvent for BetaEvent {
        fn event_type(&self) -> String {
            "BetaSpawned".into()
        }
        fn event_version(&self) -> String {
            "1".into()
        }
    }

    #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, thiserror::Error)]
    #[error("beta error")]
    struct BetaError;

    #[async_trait]
    impl EventSourced for Beta {
        type Id = String;
        type Event = BetaEvent;
        type Command = ();
        type Error = BetaError;
        type Jobs = Nil;
        type Materialized = Nil;

        const AGGREGATE_TYPE: &'static str = "Beta";
        const PROJECTION: Nil = Nil;
        const SCHEMA_VERSION: u64 = 1;

        fn originate(event: &BetaEvent) -> Option<Self> {
            match event {
                BetaEvent::Spawned => Some(Self { tag: "beta".into() }),
            }
        }

        fn evolve(_: &Self, _: &BetaEvent) -> Result<Option<Self>, BetaError> {
            Ok(None)
        }

        async fn initialize(
            (): (),
            _jobs: &JobQueue<Self::Jobs>,
        ) -> Result<Vec<BetaEvent>, BetaError> {
            Ok(vec![BetaEvent::Spawned])
        }

        async fn transition(
            &self,
            (): (),
            _jobs: &JobQueue<Self::Jobs>,
        ) -> Result<Vec<BetaEvent>, BetaError> {
            Ok(vec![])
        }
    }

    crate::register_entities!(Alpha, Beta);

    type TwoEntityList = deps![Alpha, Beta];

    #[test]
    fn has_entity_inject_alpha() {
        let event = <TwoEntityList as HasEntity<Alpha>>::inject("a1".to_string(), AlphaEvent::Born);
        assert!(matches!(event, OneOf::Here(_)));
    }

    #[test]
    fn has_entity_inject_beta() {
        let event =
            <TwoEntityList as HasEntity<Beta>>::inject("b1".to_string(), BetaEvent::Spawned);
        assert!(matches!(event, OneOf::There(OneOf::Here(_))));
    }

    #[tokio::test]
    async fn on_chain_handles_alpha_event() {
        let event = <TwoEntityList as HasEntity<Alpha>>::inject("a1".to_string(), AlphaEvent::Born);

        let result = event
            .on(|id, event| async move { format!("alpha:{id}:{event:?}") })
            .on(|id, event| async move { format!("beta:{id}:{event:?}") })
            .exhaustive()
            .await;

        assert_eq!(result, "alpha:a1:Born");
    }

    #[tokio::test]
    async fn on_chain_handles_beta_event() {
        let event =
            <TwoEntityList as HasEntity<Beta>>::inject("b1".to_string(), BetaEvent::Spawned);

        let result = event
            .on(|id, event| async move { format!("alpha:{id}:{event:?}") })
            .on(|id, event| async move { format!("beta:{id}:{event:?}") })
            .exhaustive()
            .await;

        assert_eq!(result, "beta:b1:Spawned");
    }

    #[tokio::test]
    async fn on_with_fallback_uses_normal_handler_on_success() {
        let event = <TwoEntityList as HasEntity<Alpha>>::inject("a1".to_string(), AlphaEvent::Born);

        let result: Result<String, String> = event
            .on_with_fallback(
                |id, _event| async move { Ok(format!("normal:{id}")) },
                |_error, _id, _event| async move { unreachable!("fallback should not run") },
            )
            .on(|_id, _event| async { Ok("beta".to_string()) })
            .exhaustive()
            .await;

        assert_eq!(result.unwrap(), "normal:a1");
    }

    #[tokio::test]
    async fn on_with_fallback_runs_fallback_with_event_and_error() {
        let event = <TwoEntityList as HasEntity<Alpha>>::inject("a1".to_string(), AlphaEvent::Born);

        let result: Result<String, String> = event
            .on_with_fallback(
                |_id, _event| async { Err("handler failed".to_string()) },
                |error, id, _event| async move { Ok(format!("recovered:{id}:{error}")) },
            )
            .on(|_id, _event| async { Ok("beta".to_string()) })
            .exhaustive()
            .await;

        assert_eq!(result.unwrap(), "recovered:a1:handler failed");
    }

    #[tokio::test]
    async fn on_with_fallback_on_fold_runs_fallback_with_event_and_error() {
        let event =
            <TwoEntityList as HasEntity<Beta>>::inject("b1".to_string(), BetaEvent::Spawned);

        let result: Result<String, String> = event
            .on(|_id, _event| async { Ok("alpha".to_string()) })
            .on_with_fallback(
                |_id, _event| async { Err("beta failed".to_string()) },
                |error, id, _event| async move { Ok(format!("recovered:{id}:{error}")) },
            )
            .exhaustive()
            .await;

        assert_eq!(result.unwrap(), "recovered:b1:beta failed");
    }
}
