//! Durable, retryable jobs for command side effects.
//!
//! Command handlers stay pure `(state, command) -> Vec<Event>` and
//! enqueue side effects as [`Job`]s. The framework flushes pending
//! jobs inside the same SQLite transaction that commits the
//! triggering events, so a job is enqueued iff its events commit --
//! closing the crash-safety window between a side effect and the
//! event meant to record it.
//!
//! Jobs are stored in apalis's `Jobs` table and executed by a
//! supervised apalis worker. [`perform`](Job::perform) receives the
//! consumer-owned [`Input`](Job::Input) dependency bundle.
//!
//! The queue is written through the event store's own connection
//! (sqlx 0.9), while the worker side reads it through apalis's
//! storage (sqlx 0.8). Both address the same `Jobs` table in the
//! same SQLite database.

use apalis::layers::retry::backoff::Backoff;
use apalis::prelude::{Attempt, Data};
use apalis_codec::json::JsonCodec;
use apalis_core::backend::poll_strategy::{BackoffConfig, IntervalStrategy, StrategyBuilder};
use apalis_core::worker::context::WorkerContext;
use apalis_core::worker::event::Event;
use apalis_sqlite::fetcher::SqliteFetcher;
use apalis_sqlite::{CompactType, Config, SqlitePool, SqliteStorage};
use serde::Serialize;
use serde::de::DeserializeOwned;
use std::future::Future;
use std::marker::PhantomData;
use std::sync::Arc;
use std::time::Duration;
use tracing::{debug, error, warn};

use crate::dependency::{Cons, Nil};

/// A durable, retryable unit of side-effecting work.
///
/// Each implementation is one self-contained side effect; an entity
/// declares the set of jobs its commands dispatch. The job is
/// serialized into apalis's queue and executed by a supervised
/// worker, which calls [`perform`](Job::perform) with the
/// consumer-owned [`Input`](Job::Input) dependency bundle.
pub trait Job: Serialize + DeserializeOwned + Send + 'static {
    /// Dependency bundle injected into [`perform`](Job::perform).
    ///
    /// The consumer's worker wiring constructs and owns this; the
    /// framework only forwards a shared reference.
    type Input: Send + Sync + 'static;

    /// Value produced on successful completion.
    type Output: Send + 'static;

    /// Error returned when [`perform`](Job::perform) fails.
    type Error: std::error::Error + Send + Sync + 'static;

    /// Worker name prefix; the registered worker name is
    /// `format!("{WORKER_NAME}-{index}")`.
    const WORKER_NAME: &'static str;

    /// Stable identifier for this job kind, used as the queue name
    /// in apalis's `Jobs` table, by the failure-injection registry,
    /// and in structured logs. Must be unique across job types --
    /// two kinds sharing a name would consume each other's queue.
    /// Distinct from [`WORKER_NAME`](Job::WORKER_NAME) because
    /// multiple workers can share a kind.
    ///
    /// Persisted in the database, so it must stay stable across
    /// refactors and compiler upgrades (which is why
    /// `std::any::type_name` is not used here).
    const KIND: &'static str;

    /// Logged when retries are exhausted.
    const TERMINAL_FAILURE_MSG: &'static str = "Job failed after retries";

    /// Human-readable label for structured logging.
    fn label(&self) -> Label;

    /// Execute this job against the injected input.
    fn perform(
        &self,
        input: &Self::Input,
    ) -> impl Future<Output = Result<Self::Output, Self::Error>> + Send;
}

/// Type-level list of [`Job`] types an aggregate can dispatch.
///
/// Built from [`Cons`](crate::Cons) / [`Nil`](crate::Nil) -- the same
/// cells [`deps!`](crate::deps) uses for reactor dependencies -- via
/// the [`jobs!`](crate::jobs) macro: `jobs![SendEmail, ChargeCard]`.
///
/// `Send` so the [`JobQueue`] threads through the framework's `Send`
/// command future.
pub trait JobList: Send {}

impl JobList for Nil {}

impl<Head: Job, Tail: JobList> JobList for Cons<Head, Tail> {}

/// Membership marker: `J` is one of the job types in this [`JobList`].
///
/// Bounds [`JobQueue::push`] so a handler can enqueue a job only when
/// its type is in the aggregate's declared list. The per-member impls
/// are generated by [`register_jobs!`](crate::register_jobs), which
/// [`jobs!`](crate::jobs) invokes.
pub trait HasJob<J: Job>: JobList {}

/// Single-element list: its one member is trivially present.
impl<J: Job> HasJob<J> for Cons<J, Nil> {}

/// Handler-facing handle for enqueuing the [`Job`]s an aggregate declares.
///
/// Generic over the aggregate's [`JobList`].
/// [`push`](Self::push) / [`push_with_delay`](Self::push_with_delay)
/// are synchronous and merely *buffer* onto the handle, and accept only
/// job types in the list (`Jobs: HasJob<J>`). The framework drains the
/// buffer inside the event-commit transaction, so enqueue is atomic with
/// the triggering events and the handler stays I/O-free.
///
/// Constructed fresh per command by the framework and dropped at the
/// end of the call.
pub struct JobQueue<Jobs: JobList> {
    buffered: Vec<PendingPush>,
    _jobs: PhantomData<Jobs>,
}

impl<Jobs: JobList> JobQueue<Jobs> {
    /// Buffers a job for execution as soon as the events commit.
    ///
    /// Compiles only when `J` is one of the aggregate's declared job
    /// types (`Jobs: HasJob<J>`).
    pub fn push<J: Job>(&mut self, job: J)
    where
        Jobs: HasJob<J>,
    {
        self.buffered.push(PendingPush {
            job: Box::new(job),
            delay: None,
        });
    }

    /// Buffers a job to run no earlier than `delay` after commit.
    pub fn push_with_delay<J: Job>(&mut self, job: J, delay: Duration)
    where
        Jobs: HasJob<J>,
    {
        self.buffered.push(PendingPush {
            job: Box::new(job),
            delay: Some(delay),
        });
    }

    fn into_pending(self) -> Vec<PendingPush> {
        self.buffered
    }
}

impl<Jobs: JobList> Default for JobQueue<Jobs> {
    fn default() -> Self {
        Self {
            buffered: Vec::new(),
            _jobs: PhantomData,
        }
    }
}

/// A buffered push, type-erased so one queue can hold heterogeneous job
/// types. The concrete type is recovered at flush only to write the
/// `job_type` and JSON payload.
struct PendingPush {
    job: Box<dyn ErasedJob>,
    delay: Option<Duration>,
}

/// Type-erased view of a buffered [`Job`].
trait ErasedJob: Send {
    fn job_type(&self) -> &'static str;
    fn encode(&self) -> Result<Vec<u8>, serde_json::Error>;
}

impl<J: Job> ErasedJob for J {
    fn job_type(&self) -> &'static str {
        J::KIND
    }

    fn encode(&self) -> Result<Vec<u8>, serde_json::Error> {
        serde_json::to_vec(self)
    }
}

/// Builds a type-level [`JobList`] from job types: `jobs![A, B]`
/// expands to `Cons<A, Cons<B, Nil>>`, and `jobs![]` to `Nil`.
///
/// In statement position, declare the list and generate its
/// [`HasJob`] impls in one call with
/// [`register_jobs!`](crate::register_jobs).
#[macro_export]
macro_rules! jobs {
    () => { $crate::Nil };
    ($head:ty $(, $tail:ty)* $(,)?) => {
        $crate::Cons<$head, $crate::jobs![$($tail),*]>
    };
}

/// Generates the [`HasJob`] impls for each member of a job list, so
/// `JobQueue::push` accepts every declared job type.
///
/// A single-element list is covered by a blanket impl, so this is a
/// no-op there; multi-element lists need the generated impls.
#[macro_export]
macro_rules! register_jobs {
    ($single:ty) => {};

    ($($job:ty),+ $(,)?) => {
        $crate::register_jobs!(@impls [$($job),+] [$($job),+]);
    };

    (@impls [] [$($all:ty),+]) => {};

    (@impls [$current:ty $(, $rest:ty)*] [$($all:ty),+]) => {
        impl $crate::HasJob<$current> for $crate::jobs![$($all),+] {}

        $crate::register_jobs!(@impls [$($rest),*] [$($all),+]);
    };
}

/// Worker-side handle to apalis's SQLite storage for a single job
/// type.
///
/// Built once at startup from a pool addressing the same database as
/// the event store. Consumed by the worker wiring via
/// [`into_storage`](Self::into_storage).
pub struct JobBackend<J: Job> {
    storage: Storage<J>,
}

impl<J: Job> JobBackend<J> {
    /// Builds a backend over apalis's `Jobs` table in `pool`.
    ///
    /// `pool` is an apalis (sqlx 0.8) pool; the same database is
    /// written by the event store's own connection at enqueue time.
    #[must_use]
    pub fn new(pool: &SqlitePool) -> Self {
        Self {
            storage: SqliteStorage::new_with_config(pool, &build_poll_config::<J>()),
        }
    }

    /// Consumes the backend, yielding the apalis storage for worker
    /// registration.
    #[must_use]
    pub fn into_storage(self) -> Storage<J> {
        self.storage
    }

    /// The pool backing this storage, for queue maintenance.
    #[must_use]
    pub fn pool(&self) -> &SqlitePool {
        self.storage.pool()
    }
}

/// Error returned by the worker handler when a job fails or is
/// deliberately failed by the injector.
#[derive(Debug, thiserror::Error)]
pub enum JobError {
    /// The job's own [`perform`](Job::perform) returned an error.
    #[error("{label}: {source}")]
    Failed {
        /// Label of the failed job instance.
        label: Label,
        /// The underlying domain error.
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },

    /// A failure injected by [`FailureInjector`] for fault testing.
    #[cfg(any(test, feature = "test-support"))]
    #[error("injected terminal job failure")]
    Injected,
}

/// Error raised while flushing buffered jobs into apalis's queue.
#[derive(Debug, thiserror::Error)]
pub enum QueuePushError {
    /// The job payload could not be JSON-encoded.
    #[error("failed to encode job payload")]
    Encode(#[from] serde_json::Error),
    /// The job row could not be written.
    #[error("failed to write job row")]
    Sql(#[from] sqlx::Error),
    /// The requested delay exceeds the representable range.
    #[error("job delay exceeds the representable range")]
    DelayOverflow(#[from] std::num::TryFromIntError),
}

/// Human-readable identifier for a job instance, used in logs and
/// failure-injection targeting.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Label(String);

impl Label {
    /// Wraps a string-like value as a label.
    pub fn new(label: impl Into<String>) -> Self {
        Self(label.into())
    }
}

impl std::fmt::Display for Label {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&self.0)
    }
}

/// Circuit-breaker recovery timeout. Set effectively infinite: a
/// tripped breaker stays open until the supervisor restarts, since a
/// terminal job failure indicates a problem a human must inspect.
pub const FAIL_STOP_RECOVERY_TIMEOUT: Duration = Duration::from_secs(60 * 60 * 24 * 365);

/// Retry backoff applied to job execution: 1s base, doubling, capped
/// at 30s.
pub const RETRY_BACKOFF: ExponentialBackoff =
    ExponentialBackoff::new(Duration::from_secs(1), Duration::from_secs(30));

/// Exponential backoff for apalis retries.
#[derive(Clone, Debug)]
pub struct ExponentialBackoff {
    base: Duration,
    max: Duration,
    iteration: u32,
}

impl ExponentialBackoff {
    /// Creates a backoff that starts at `base` and doubles up to
    /// `max`.
    #[must_use]
    pub const fn new(base: Duration, max: Duration) -> Self {
        Self {
            base,
            max,
            iteration: 0,
        }
    }
}

impl Backoff for ExponentialBackoff {
    type Future = tokio::time::Sleep;

    fn next_backoff(&mut self) -> Self::Future {
        let factor = 2u32.saturating_pow(self.iteration);
        let delay = self.base.saturating_mul(factor).min(self.max);
        self.iteration = self.iteration.saturating_add(1);
        tokio::time::sleep(delay)
    }
}

/// apalis SQLite storage specialized for a single job type with JSON
/// payload encoding.
pub type Storage<J> = SqliteStorage<J, JsonCodec<CompactType>, SqliteFetcher>;

/// The apalis worker handler. Deserializes the job, logs, and runs
/// [`perform`](Job::perform) against the injected input.
#[cfg(not(any(test, feature = "test-support")))]
pub async fn work<J>(
    job: J,
    input: Data<Arc<J::Input>>,
    attempt: Attempt,
) -> Result<J::Output, JobError>
where
    J: Job + Sync,
{
    let label = job.label();
    log_processing(&label, attempt.current());
    job.perform(&input)
        .await
        .map_err(|source| JobError::Failed {
            label,
            source: Box::new(source),
        })
}

/// Test-support [`work`] variant that routes execution through a
/// [`FailureInjector`] so end-to-end tests can force a terminal
/// failure for a targeted job.
#[cfg(any(test, feature = "test-support"))]
pub async fn work<J>(
    job: J,
    input: Data<Arc<J::Input>>,
    injector: Data<FailureInjector>,
    attempt: Attempt,
) -> Result<J::Output, JobError>
where
    J: Job + Sync,
{
    injector.perform::<J>(&job, &input, attempt.current()).await
}

/// Worker event handler that stops the worker and notifies the
/// supervisor on a terminal (retries-exhausted) failure.
pub fn on_terminal_failure(
    failure_notify: Arc<tokio::sync::Notify>,
    error_msg: &'static str,
) -> impl Fn(&WorkerContext, &Event) + Send + Sync + 'static {
    move |context, event| {
        if let Event::Error(error) = event {
            error!(%error, worker = %context.name(), "{error_msg}");
            // notify_one stores a permit when no task is awaiting, so
            // the signal is not lost if the supervisor has not reached
            // its `notified().await` yet (notify_waiters would drop it).
            failure_notify.notify_one();
            let _ = context.stop();
        }
    }
}

/// Builds a supervised apalis worker for a [`Job`] type, applying the
/// library's standard concurrency, retry policy, circuit breaker, and
/// terminal-failure handling.
///
/// Pass `::<JobType>`, a worker index, the job's [`JobBackend`], an
/// `Arc<JobType::Input>`, a
/// [`CircuitBreakerConfig`](crate::CircuitBreakerConfig), and an
/// `Arc<tokio::sync::Notify>` signalled on terminal failure. Under
/// `test-support`, also pass a [`FailureInjector`]. Register the
/// returned worker with a [`Monitor`](crate::Monitor).
#[macro_export]
macro_rules! build_supervised_worker {
    (
        ::<$job:ty>,
        $index:expr,
        $backend:expr,
        $input:expr,
        $fail_stop:expr,
        $failure_notify:expr
        $(, $failure_injector:expr)? $(,)?
    ) => {{
        use $crate::__apalis::{
            CircuitBreaker, EventListenerExt, RetryPolicy, WorkerBuilder, WorkerBuilderExt,
        };

        let builder = WorkerBuilder::new(::std::format!(
            "{}-{}",
            <$job as $crate::Job>::WORKER_NAME,
            $index,
        ))
        .backend($backend.into_storage())
        .data($input);

        $(
            let builder = builder.data($failure_injector);
        )?

        builder
            .concurrency(1)
            .retry(RetryPolicy::retries(3).with_backoff($crate::RETRY_BACKOFF.clone()))
            .break_circuit_with($fail_stop)
            .on_event($crate::on_terminal_failure(
                $failure_notify,
                <$job as $crate::Job>::TERMINAL_FAILURE_MSG,
            ))
            .build($crate::work::<$job>)
    }};
}

/// Writes buffered pushes into apalis's `Jobs` table through `connection`.
///
/// Rows are written in apalis's storage format -- JSON-encoded payload,
/// `Pending` status, the job type as the queue name -- so the worker's
/// fetcher picks them up.
async fn insert_pending(
    connection: &mut sqlx::SqliteConnection,
    pending: Vec<PendingPush>,
) -> Result<(), QueuePushError> {
    for push in pending {
        let job_type = push.job.job_type();
        let payload = push.job.encode()?;
        let delay_secs = match push.delay {
            None => 0_i64,
            Some(delay) => i64::try_from(delay.as_secs())?,
        };
        let id = ulid::Ulid::new().to_string();

        sqlx::query(
            "INSERT INTO Jobs (job, id, job_type, run_at) \
             VALUES (?1, ?2, ?3, CAST(strftime('%s', 'now') AS INTEGER) + ?4)",
        )
        .bind(payload)
        .bind(id)
        .bind(job_type)
        .bind(delay_secs)
        .execute(&mut *connection)
        .await?;
    }

    Ok(())
}

/// Drains a [`JobQueue`] into apalis's `Jobs` table through `connection`.
///
/// Called by the framework inside the event-commit transaction so a job
/// becomes visible to the worker iff its triggering events commit.
#[doc(hidden)]
pub async fn flush_jobs<Jobs: JobList>(
    connection: &mut sqlx::SqliteConnection,
    queue: JobQueue<Jobs>,
) -> Result<(), QueuePushError> {
    insert_pending(connection, queue.into_pending()).await
}

tokio::task_local! {
    /// Per-command buffer of jobs awaiting flush. Scoped by
    /// [`with_pending_jobs`] around command execution, populated by the
    /// [`Lifecycle`](crate::Lifecycle) handler, and drained by the event
    /// repository inside its commit transaction.
    static PENDING_JOBS: std::cell::RefCell<Vec<PendingPush>>;
}

/// Runs `future` with a fresh per-command pending-jobs buffer in scope, so
/// the jobs a handler enqueues are flushed in the same transaction that
/// commits its events.
pub(crate) async fn with_pending_jobs<F>(future: F) -> F::Output
where
    F: Future,
{
    PENDING_JOBS
        .scope(std::cell::RefCell::new(Vec::new()), future)
        .await
}

/// Buffers a handler's [`JobQueue`] for the framework to flush at commit.
///
/// A no-op when the queue is empty. If jobs are present but no
/// [`with_pending_jobs`] scope is active (a programming error -- handlers
/// run inside [`Store::send`](crate::Store::send)), they are dropped with a
/// warning rather than silently lost.
pub(crate) fn buffer_pending<Jobs: JobList>(queue: JobQueue<Jobs>) {
    let pending = queue.into_pending();
    if pending.is_empty() {
        return;
    }

    let count = pending.len();
    if PENDING_JOBS
        .try_with(move |cell| cell.borrow_mut().extend(pending))
        .is_err()
    {
        warn!(target: "job", count, "jobs enqueued outside a command scope were dropped");
    }
}

/// Flushes the current command's buffered jobs through `connection`.
///
/// Called by the event repository inside its commit transaction; a no-op
/// when no scope is active or nothing was buffered.
pub(crate) async fn flush_pending_jobs(
    connection: &mut sqlx::SqliteConnection,
) -> Result<(), QueuePushError> {
    let pending = PENDING_JOBS
        .try_with(|cell| std::mem::take(&mut *cell.borrow_mut()))
        .unwrap_or_default();
    insert_pending(connection, pending).await
}

fn build_poll_config<J: Job>() -> Config {
    let strategy = StrategyBuilder::new()
        .apply(
            IntervalStrategy::new(Duration::from_millis(100))
                .with_backoff(BackoffConfig::new(Duration::from_secs(1))),
        )
        .build();

    Config::new(J::KIND).with_poll_interval(strategy)
}

fn log_processing(label: &Label, attempt: usize) {
    debug!(target: "job", %label, attempt, "processing job");
}

/// Fault-injection registry for end-to-end terminal-failure tests.
///
/// [`arm`](Self::arm) marks a [`Job::KIND`] so the next job of that
/// kind fails terminally; the failure then sticks to that specific
/// job instance (by [`Label`]) so retries of it keep failing while
/// other instances of the same kind run normally.
#[cfg(any(test, feature = "test-support"))]
#[derive(Clone, Debug, Default)]
pub struct FailureInjector {
    states: Arc<std::sync::Mutex<std::collections::HashMap<&'static str, InjectionState>>>,
}

#[cfg(any(test, feature = "test-support"))]
#[derive(Debug, Default)]
enum InjectionState {
    #[default]
    Idle,
    Armed,
    Targeted(Label),
}

#[cfg(any(test, feature = "test-support"))]
impl FailureInjector {
    /// Creates an injector with no kinds armed.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Arms injection for the next job of `kind`.
    pub fn arm(&self, kind: &'static str) {
        self.lock().insert(kind, InjectionState::Armed);
    }

    fn should_inject(&self, kind: &'static str, label: &Label) -> bool {
        let mut guard = self.lock();
        let state = guard.entry(kind).or_default();
        let inject = match state {
            InjectionState::Idle => false,
            InjectionState::Armed => {
                *state = InjectionState::Targeted(label.clone());
                true
            }
            InjectionState::Targeted(target) => target == label,
        };
        drop(guard);
        inject
    }

    fn lock(
        &self,
    ) -> std::sync::MutexGuard<'_, std::collections::HashMap<&'static str, InjectionState>> {
        self.states
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
    }

    async fn perform<J: Job + Sync>(
        &self,
        job: &J,
        input: &J::Input,
        attempt: usize,
    ) -> Result<J::Output, JobError> {
        let label = job.label();
        if self.should_inject(J::KIND, &label) {
            return Err(JobError::Injected);
        }
        log_processing(&label, attempt);
        job.perform(input).await.map_err(|source| JobError::Failed {
            label,
            source: Box::new(source),
        })
    }
}

#[cfg(test)]
mod tests {
    use serde::{Deserialize, Serialize};
    use std::convert::Infallible;

    use super::*;

    async fn jobs_pool() -> sqlx::SqlitePool {
        const JOBS_SCHEMA: &str = "CREATE TABLE Jobs ( \
             job BLOB NOT NULL, \
             id TEXT NOT NULL UNIQUE, \
             job_type TEXT NOT NULL, \
             status TEXT NOT NULL DEFAULT 'Pending', \
             attempts INTEGER NOT NULL DEFAULT 0, \
             max_attempts INTEGER NOT NULL DEFAULT 25, \
             run_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now')), \
             last_result TEXT, \
             lock_at INTEGER, \
             lock_by TEXT, \
             done_at INTEGER, \
             priority INTEGER NOT NULL DEFAULT 0, \
             metadata TEXT, \
             idempotency_key TEXT, \
             PRIMARY KEY(id) \
         )";

        let pool = sqlx::SqlitePool::connect(":memory:").await.unwrap();
        sqlx::query(JOBS_SCHEMA).execute(&pool).await.unwrap();
        pool
    }

    #[derive(Debug, Serialize, Deserialize)]
    enum SendEmail {
        Welcome { address: String },
        Reminder { address: String },
    }

    impl Job for SendEmail {
        type Input = ();
        type Output = ();
        type Error = Infallible;

        const WORKER_NAME: &'static str = "send-email";
        const KIND: &'static str = "send-email";

        fn label(&self) -> Label {
            match self {
                Self::Welcome { address } => Label::new(format!("welcome:{address}")),
                Self::Reminder { address } => Label::new(format!("reminder:{address}")),
            }
        }

        async fn perform(&self, _input: &()) -> Result<(), Infallible> {
            Ok(())
        }
    }

    #[derive(Debug, Serialize, Deserialize)]
    struct ChargeCard {
        cents: u64,
    }

    impl Job for ChargeCard {
        type Input = ();
        type Output = ();
        type Error = Infallible;

        const WORKER_NAME: &'static str = "charge-card";
        const KIND: &'static str = "charge-card";

        fn label(&self) -> Label {
            Label::new(format!("charge:{}", self.cents))
        }

        async fn perform(&self, _input: &()) -> Result<(), Infallible> {
            Ok(())
        }
    }

    crate::register_jobs!(SendEmail, ChargeCard);

    #[test]
    fn label_reflects_variant_and_renders_via_display() {
        let welcome = SendEmail::Welcome {
            address: "a@example.com".to_string(),
        };
        let reminder = SendEmail::Reminder {
            address: "b@example.com".to_string(),
        };

        assert_eq!(welcome.label().to_string(), "welcome:a@example.com");
        assert_eq!(reminder.label().to_string(), "reminder:b@example.com");
    }

    #[tokio::test(start_paused = true)]
    async fn backoff_doubles_from_base_and_caps_at_max() {
        let mut backoff = ExponentialBackoff::new(Duration::from_secs(1), Duration::from_secs(30));

        for expected_seconds in [1, 2, 4, 8, 16, 30, 30] {
            let sleep = backoff.next_backoff();
            assert_eq!(
                sleep.deadline() - tokio::time::Instant::now(),
                Duration::from_secs(expected_seconds),
                "backoff delay must double from base and cap at max"
            );
        }
    }

    #[tokio::test(start_paused = true)]
    async fn backoff_saturates_instead_of_overflowing() {
        let mut backoff = ExponentialBackoff::new(Duration::from_secs(1), Duration::MAX);
        backoff.iteration = u32::MAX;

        // The doubling factor saturates at u32::MAX instead of
        // overflowing, so the uncapped delay is base * u32::MAX.
        let sleep = backoff.next_backoff();
        assert_eq!(
            sleep.deadline() - tokio::time::Instant::now(),
            Duration::from_secs(u64::from(u32::MAX)),
        );

        // A second call must not panic on the iteration counter and
        // keeps yielding the saturated delay.
        let next = backoff.next_backoff();
        assert_eq!(
            next.deadline() - tokio::time::Instant::now(),
            Duration::from_secs(u64::from(u32::MAX)),
        );
    }

    #[tokio::test]
    async fn injector_targets_first_armed_instance_and_spares_others() {
        let injector = FailureInjector::new();
        injector.arm(SendEmail::KIND);

        let welcome = SendEmail::Welcome {
            address: "a@example.com".to_string(),
        };
        let reminder = SendEmail::Reminder {
            address: "b@example.com".to_string(),
        };

        let first = injector.perform(&welcome, &(), 1).await;
        assert!(matches!(first, Err(JobError::Injected)));

        let retry = injector.perform(&welcome, &(), 2).await;
        assert!(
            matches!(retry, Err(JobError::Injected)),
            "the injected failure must stick to the targeted instance across retries"
        );

        injector.perform(&reminder, &(), 1).await.unwrap();
    }

    #[tokio::test]
    async fn build_supervised_worker_constructs_a_worker() {
        let pool = apalis_sqlite::SqlitePool::connect(":memory:")
            .await
            .unwrap();
        let backend = JobBackend::<SendEmail>::new(&pool);

        let input = Arc::new(());
        let fail_stop = crate::CircuitBreakerConfig::default()
            .with_recovery_timeout(FAIL_STOP_RECOVERY_TIMEOUT);
        let failure_notify = Arc::new(tokio::sync::Notify::new());
        let injector = FailureInjector::new();

        let _worker = crate::build_supervised_worker!(
            ::<SendEmail>,
            0,
            backend,
            input,
            fail_stop,
            failure_notify,
            injector,
        );
    }

    #[tokio::test]
    async fn flush_writes_an_apalis_compatible_pending_row() {
        let pool = jobs_pool().await;

        let mut queue = JobQueue::<crate::jobs![SendEmail]>::default();
        queue.push(SendEmail::Welcome {
            address: "a@example.com".to_string(),
        });

        let mut transaction = pool.begin().await.unwrap();
        flush_jobs(&mut transaction, queue).await.unwrap();
        transaction.commit().await.unwrap();

        let (payload, job_type, status): (Vec<u8>, String, String) =
            sqlx::query_as("SELECT job, job_type, status FROM Jobs")
                .fetch_one(&pool)
                .await
                .unwrap();

        assert_eq!(job_type, SendEmail::KIND);
        assert_eq!(status, "Pending");
        let decoded: SendEmail = serde_json::from_slice(&payload).unwrap();
        assert!(matches!(decoded, SendEmail::Welcome { address } if address == "a@example.com"));
    }

    #[tokio::test]
    async fn flush_writes_distinct_rows_for_multiple_job_types() {
        let pool = jobs_pool().await;

        let mut queue = JobQueue::<crate::jobs![SendEmail, ChargeCard]>::default();
        queue.push(SendEmail::Welcome {
            address: "a@example.com".to_string(),
        });
        queue.push(ChargeCard { cents: 4200 });

        let mut transaction = pool.begin().await.unwrap();
        flush_jobs(&mut transaction, queue).await.unwrap();
        transaction.commit().await.unwrap();

        let rows: Vec<(String,)> = sqlx::query_as("SELECT job_type FROM Jobs ORDER BY job_type")
            .fetch_all(&pool)
            .await
            .unwrap();

        let job_types: Vec<String> = rows.into_iter().map(|(job_type,)| job_type).collect();
        assert_eq!(job_types.len(), 2);
        assert!(job_types.contains(&ChargeCard::KIND.to_string()));
        assert!(job_types.contains(&SendEmail::KIND.to_string()));
    }
}
